version: '3.7'
services:
  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - '9091:9091'
    networks:
      - wwatch

networks:
  wwatch:               # see https://github.com/netflame/wwatch
    name: wwatch-net
    external: true